# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  Default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warFile'
    publishLocation: 'Container'

- powershell: |
    $tomcatVersion = "9"
    $downloadUrl = "https://downloads.apache.org/tomcat/tomcat-9/v9.0.86/bin/apache-tomcat-9.0.86.zip"
    $downloadPath = "$(Build.ArtifactStagingDirectory)/tomcat/tomcat.zip"
    $extractPath = "$(Agent.TempDirectory)/Tomcat"

    # Create the target directory if it doesn't exist
    New-Item -ItemType Directory -Force -Path $(Split-Path $downloadPath)

    Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath
    Expand-Archive -Path $downloadPath -DestinationPath $extractPath

    # Set Tomcat bin directory path
    $catalinaBinPath = Join-Path $extractPath "apache-tomcat-9.0.86/bin"

    Write-Host "Checking if Tomcat bin directory exists: $catalinaBinPath"

    # Ensure the path exists before changing location
    if (Test-Path $catalinaBinPath -PathType Container) {
        Set-Location -Path $catalinaBinPath

        # Start Tomcat on port 9080
        $catalinaBatPath = Join-Path $catalinaBinPath "catalina.bat"
        $arguments = "run", "-Dcatalina.http.port=9080"

        Write-Host "Executing: $catalinaBatPath $arguments"

        # Start Tomcat with enhanced debugging
        Start-Process -FilePath $catalinaBatPath -ArgumentList $arguments -NoNewWindow -Wait
    } else {
        Write-Host "Error: Tomcat bin directory not found."
        exit 1
    }
  displayName: 'Download, Extract, and Start Tomcat'
