trigger:
- master

pool:
  Default

steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    artifactName: 'tomcat-artifact'
    downloadPath: '$(Build.ArtifactStagingDirectory)/tomcat'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/tomcat/*.zip'
    destinationFolder: '$(Agent.TempDirectory)/Tomcat'

- script: |
    echo "##vso[task.setvariable variable=CATALINA_HOME;isOutput=true]$(Agent.TempDirectory)/Tomcat/apache-tomcat-<version>"
    echo "##vso[task.setvariable variable=CATALINA_BASE;isOutput=true]$(Agent.TempDirectory)/Tomcat/apache-tomcat-<version>"
  displayName: 'Set Tomcat Environment Variables'

- script: '$(CATALINA_HOME)/bin/startup.bat'
  displayName: 'Start Tomcat'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warFile'
    publishLocation: 'Container'
